### ISSUE TITLE
TypeScript and autocomplete

### ISSUE THREAD

**Issue by robertherber** [lukehaas/RunJS#122]
I've just switched to TypeScript. The tooling around it (mainly VSCode) makes it so smooth. Above all - and most interesting for the RunJS case - it allows for autocompleting and inline documenting of third-party library calls. Would be awesome if RunJS could support autocompleting in a similar way!

**Comment by lukehaas** [comment]
👍aiming to have all this in RunJS at some point. Hopefully later this year.

**Comment by flpwgr** [comment]
Would be possible to use Monaco Editor instead of CodeMirror?

**Comment by hoegertn** [comment]
Any ETA on this?

**Comment by lukehaas** [comment]
@hoegertn actively working on this whenever I find the time. It's a bigger feature than I initially expected, couldn't give you an accurate ETA.

**Comment by mknmohit** [comment]
Thanks @lukehaas for actively looking into this. I would love to see the inline errors on hover, something like in the below attachment. ❤️ 
![image](https://user-images.githubusercontent.com/19211475/114667977-c8003000-9d1d-11eb-8b1d-911ce83342d3.png)

**Comment by lukehaas** [comment]
@robertherber @hoegertn @mknmohit The latest version of RunJS supports type checking and autocomplete 🎉

**Comment by lordlycastle** [comment]
Should we create new issue for the hover over vars and errors (squiggly lines) to see the pop-up like you do for TS playground? That is a very missed feature which JS devs don't care about.

**Comment by lukehaas** [comment]
@lordlycastle it's already supported behind the type checking option.

**Comment by lordlycastle** [comment]
@lukehaas I don’t understand. Is the hover pop up already implemented?

Because I noticed that it would accept incorrect TS code with type errors and still run the code after it. And there was no way to see what the error is; I only see squiggly line under it. 

We wish to see any TS compile errors and also type resolution for any var when you hover over it. Similar to VSCode or TS Play of IntelliJ.

**Comment by lukehaas** [comment]
@lordlycastle Yes, the hover popup is implemented:

![Screenshot 2021-07-22 at 21 28 02](https://user-images.githubusercontent.com/741344/126705300-1ee035ef-0dbc-4254-a3ed-97fca52e9200.png)

**Comment by lordlycastle** [comment]
@lukehaas nice! In that case I have a bug a report. It didn't work with my 1 char var name. 

And a features request to show TS errors first rather than linting issues or TS warnings. For example, here it should complain more about type error rather than variable not used.

<img width="398" alt="SS 2021-07-27T17 53 30@2x" src="https://user-images.githubusercontent.com/11729541/127186633-160b12c0-f0c0-4b41-b579-adb81a6b9e52.png">

**Comment by lukehaas** [comment]
Thanks @lordlycastle, I'll look into it.

Regarding TS errors, are you sure you have TS turned on? I'm seeing a different error to you:

![Screenshot 2021-07-27 at 17 10 48](https://user-images.githubusercontent.com/741344/127189319-5b89b1c8-0143-453a-8af0-f9a992ca429f.png)

**Comment by lordlycastle** [comment]
@lukehaas think I found the cause. Adding an `import` statement seems to change the error shown. See below.

https://user-images.githubusercontent.com/11729541/127193359-6af5e1ea-f818-439c-9556-66f7928090d6.mp4

**Comment by lukehaas** [comment]
@lordlycastle thanks, I see it now.
