### ISSUE TITLE
[Feature Request] Multiple Windows

### ISSUE THREAD

**Issue by izuchukwu** [lukehaas/RunJS#175]
Being able to hit `Cmd-N` and open a new window of RunJS would be wonderful! I find myself deleting content I'd rather temporarily keep a lot so that the right-side output is less noisy for my next set of JS testing.

**Comment by yonifra** [comment]
I was about to open an issue to allow support in tabs, and I think this is quite similar.
I use RunJS mainly for testing JS behavior, and as a sandbox for writing JS scripts, therefore, I don't want to save as much as I would like to experiment with JS. I find myself a lot of times having to start a new file, and since I have only one editor I need to discard / save my current file to start a new experiment. I think that tabs would be a killer feature for the next iteration of RunJS

**Comment by derheap** [comment]
Tabs would be absolutly great! An essential feature!

**Comment by lukehaas** [comment]
@izuchukwu @yonifra @derheap Tabs are now supported in the latest version of RunJS 🎉
