### ISSUE TITLE
Console not showing all data

### ISSUE THREAD

**Issue by alexdevero** [lukehaas/RunJS#176]
When I make a request with fetch and try to print the whole response object the output show empty object. If  try the same in the browser, printing response object will show all content.

RunJS:
![br 2](https://user-images.githubusercontent.com/4237724/92325234-3d4da900-f049-11ea-9710-deaf7880a634.png)

Browser:
![br 1](https://user-images.githubusercontent.com/4237724/92325237-42125d00-f049-11ea-9e67-d1c1a160944a.png)

RunJS version: 1.11.0.0
OS: Windows 10

I am not sure if this is a bug.

**Comment by lukehaas** [comment]
The response from the fetch API is an instance of Body, more details available here: https://developer.mozilla.org/en-US/docs/Web/API/Body

To get the output you're looking for you will need to call the `.json()` method on the response, like this:
```
fetch('https://sv443.net/jokeapi/v2/joke/Programming').
then(response => response.json())
```
The reason you're seeing something different in the chrome console is because the REPL there doesn't show you the true output of your code, it shows you modified output, which I think can be misleading. This is where RunJS differs philosophically with the chrome console as RunJS always aims to only show true responses.

**Comment by alexdevero** [comment]
@lukehaas Thanks. You are correct. It is necessary to call `json()`, `text()`, etc. on the response to parse it to readable data. I was surprised that RunJS didn't allow to log the response object itself. Are there other use cases where RunJS and chrome console will differ?

**Comment by lukehaas** [comment]
@alexdevero just taken a second look at this, I realised the Chrome console is just showing the instance properties of the response object, so not coercing the response as I thought before.
RunJS doesn't currently show instance properties because, in a lot of cases, it creates a lot of noise in the output panel and doesn't always provide much value. I do see that in this case it could be valuable to see the properties of the response. I will consider how this could be handled, maybe as an option, in RunJS in the future.

**Comment by lukehaas** [comment]
@alexdevero RunJS now displays the __proto__ object for instances such as this one.

![Screenshot 2020-11-08 at 18 59 17](https://user-images.githubusercontent.com/741344/98481782-ac37b180-21f4-11eb-8895-c65b358beaec.png)
