### ISSUE TITLE
Duplicate HTTPS requests

### ISSUE THREAD

**Issue by alankleindev** [lukehaas/RunJS#177]
Hello, I upgraded to the latest release of RunJS, 1.11.0, (also saw this in 1.09.0) and when testing with axios and node-fetch, I see duplicate/identical HTTPS requests made when there should be only one to my server. When I copy the same code and run it directly from node, I only see a single HTTPS request. Any ideas?  They are bot `GET` requests. Thanks and great tool!

```
import axios from 'axios';
import fetch from 'node-fetch'

function myPromise () {
  return new Promise((resolve, reject) => {
    fetch('https://myexpress/json')
  .then(response => response.json())
  .then(data => {
      resolve(data)
    }).catch(err => {
     reject(err);
  })
})}
     
let promises = [];
     
for (let x = 0; x < 1; x++) {
  promises.push(myPromise().catch(err => {
    console.log(`${err}`) 
}))
}

Promise.all(promises)
.then(result => {
  console.log(result);
}).catch(err => {
  console.log('oh darn!')
})
```

**Comment by lukehaas** [comment]
Due to the inner-workings of RunJS some code may be run more than once in order to capture runtime-values.
You can avoid this behaviour by turning off this option in the advanced preferences:

<img width="575" alt="Screenshot 2020-09-07 at 19 19 38" src="https://user-images.githubusercontent.com/741344/92411289-29846e80-f13f-11ea-877d-a837a685b896.png">

Ideally the duplicate requests should not happen in any scenario, this may be something that gets addressed in a future version of RunJS.
