### ISSUE TITLE
leveldown can not use?

### ISSUE THREAD

**Issue by crotel** [lukehaas/RunJS#184]
Sys: macOS Catalina 10.15.5 (19F101)
RunJS : Version 1.11.0 (1.11.0)

when add module level, levelup, leveldown
error found:

`Error: dlopen(/Users/xmt/Library/Application Support/runjs/node_modules/leveldown/prebuilds/darwin-x64/node.napi.node, 1): no suitable image found.  Did find:`

Anything I miss?

**Comment by lukehaas** [comment]
@crotel this is because RunJS doesn't currently support building native modules. I'd suggest building the leveldown package manually inside the RunJS application directory.
This is located in one of these location, depending on your system:
Linux: ~/.config/runjs
Mac: ~/Library/Application\ Support/runjs
Windows: %APPDATA%

**Comment by crotel** [comment]
it's can not done yet. rebuild success but still can not found suitable image.

Is there any special options or steps I missing?

**Comment by lukehaas** [comment]
Sorry @crotel, you may need to find a JS equivalent of this package.
I'm hoping to have better support for native packages in the future.
