### ISSUE TITLE
Problem with for loop output

### ISSUE THREAD

**Issue by abdurrehman1998** [lukehaas/RunJS#186]
when I run following code:
`for (let i = 0; i < 5; ++i) {
setTimeout(() => console.log(i), 0)
}`
I get 5,0,1,2,3,4
![Screenshot 2020-10-17 194012](https://user-images.githubusercontent.com/25861787/96339861-9aa93100-10b0-11eb-9815-969e612eb389.png)

**Comment by lukehaas** [comment]
Thanks @abdurrehman1998.
The reason you're seeing an extra number here, in this case `5` is because `setTimeout` returns an ID and in this case it's ID is `5`. More detail about this is available here: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout

There are a number of ways you could avoid seeing the returned value of `setTimeout`, one is to assign it to something, for example:
```
for (let i = 0; i < 5; ++i) { 
  const id = setTimeout(() => console.log(i), 0)
}
```
![Screenshot 2020-10-17 at 16 09 39](https://user-images.githubusercontent.com/741344/96346345-3035c800-1093-11eb-9e79-be75de3ed69e.png)

Another thing you could do is disable the display of runtime values:
![Screenshot 2020-10-17 at 16 10 45](https://user-images.githubusercontent.com/741344/96346366-5491a480-1093-11eb-84e0-0fb40a334707.png)

Hope that helps.
