### ISSUE TITLE
Question on Promise Resolution Output being displayed but no equivalent console.log

### ISSUE THREAD

**Issue by alankleindev** [lukehaas/RunJS#187]
Hello, when all promises resolve successfully in my code, I am seeing the resolve text displayed, `Promise Resolved Successfully` but there is no console.log to display it. 

If I run the same code directly in node, it doesn't display the resolve text. I disabled the Advanced Option, "show runtime values".

Any suggestions on why this may be?

Thank You

```
function getRandomInt(max) {
  return Math.floor(Math.random() * Math.floor(max));
}

function myPromise() {
  let randomValue = getRandomInt(2);
  console.log(`Random Value: ${randomValue}`);
  return new Promise((resolve, reject) => {
    if (randomValue === 0) {
      setTimeout(() => resolve('Promise Resolved Successfully'), 1500);
    } else {
      reject('Promise Rejected');
    }
  });
}

myPromise()
  .then((result) => myPromise())
  .then((result) => myPromise())
  .catch((err) => console.log(`If any failures: ${err}`));

```

**Comment by lukehaas** [comment]
Thanks @alankleindev, this is an interesting one.

When runtime values are disabled RunJS will show you the output of your code as a whole, which will typically be the result of the final statement. This is the same as REPLs like the Node REPL and the Chrome console.
The simplest example of this can be seen by putting two statements into one of these REPLs.

![Screenshot 2020-10-22 at 09 08 25](https://user-images.githubusercontent.com/741344/96843492-4a322a80-1446-11eb-9fa8-8c3c6cf18627.png)

![Screenshot 2020-10-22 at 09 09 49](https://user-images.githubusercontent.com/741344/96843550-5d44fa80-1446-11eb-84b7-730e79e8b5a1.png)

The result you're seeing is the resolved response from the last statement of your code.

The reason you're not seeing the same response in the Node REPL could be due to the delayed resolution of the promise. As the Node REPL seems to show the resolved response for instantly resolved promises:

![Screenshot 2020-10-22 at 09 13 50](https://user-images.githubusercontent.com/741344/96844031-ec521280-1446-11eb-8099-6352370befee.png)

The Chrome console will give you the same result as RunJS but only if the `setTimeout` is removed so that the promise resolves instantly.
![Screenshot 2020-10-22 at 09 17 07](https://user-images.githubusercontent.com/741344/96846384-bd896b80-1449-11eb-91f4-46aa9a59a423.png)

This tells me that they have a race condition that prevents delayed responses, while RunJS does not. This is why RunJS will still show the resolved response in your example.

**Comment by alankleindev** [comment]
Thanks Luke for the detailed explanation. I really enjoy using RunJS, keep up the great work.
