### ISSUE TITLE
wrapping of arrays

### ISSUE THREAD

**Issue by matthias-schmidt** [lukehaas/RunJS#243]
Hi,

in the output, arrays get wrapped although there is plenty of space left. Is there a way to circumvent that? Tried "lineWrap": false in the config but this only affects the input part.

Thanks for the app anyway:)

**Comment by lukehaas** [comment]
@matthias-schmidt thanks for raising this as I'm happy to have a discussion about it.

The reason for the wrapped output is because the output gets formatted before it reaches the output pane. This is done with the aim of making the output more readable.

For example, without this formatting, simple arrays might look ok but an object such as `Math` will look jumbled and hard to read:

![Screenshot 2021-04-26 at 12 57 29](https://user-images.githubusercontent.com/741344/116079070-4c906e00-a68f-11eb-8480-fca200c2d1ef.png)

Here's the `Math` object with the current formatting:
![Screenshot 2021-04-26 at 13 00 56](https://user-images.githubusercontent.com/741344/116079277-82cded80-a68f-11eb-8f80-b3fb9bc336a7.png)

**Comment by matthias-schmidt** [comment]
I see. Maybe one could handle this by differentiating array-like objects by the type of their entries (primitive or not) or by adding a wrapping parameter set either in the config or in the environment variables?

**Comment by lukehaas** [comment]
Yeah, I've had a think. There could be a way I can improve this. Thanks for raising it.

**Comment by matthias-schmidt** [comment]
Thanks for taking this up:)

**Comment by lukehaas** [comment]
@matthias-schmidt array wrapping has been updated in the latest release.

**Comment by matthias-schmidt** [comment]
Thanks!

    Am Donnerstag, 8. Juli 2021, 10:25:14 MESZ hat Luke Haas ***@***.***> Folgendes geschrieben:  
 
 


@matthias-schmidt array wrapping has been updated in the latest release.
