### ISSUE TITLE
Functions in logged prototypes are ignored 

### ISSUE THREAD

**Issue by rscharfer** [lukehaas/RunJS#246]
I am sure this is a known thing, but just in case it is not...  For some reason, prototypes, if they only include functions as most do, are logged as empty objects.    It would be great if you saw all "own" properties on the prototype as well.

![image](https://user-images.githubusercontent.com/4295997/116603493-d3d52000-a8e1-11eb-96eb-c4ad50a41650.png)

**Comment by lukehaas** [comment]
Yep, this is due to some limitations with Node's util.inspect. The lack of visibility here is not due to the properties being functions but due to them being non-enumerable.
However, this is only an issue when accessing the prototype directly. If you just output `bob` here, you'll see its prototype.
