### ISSUE TITLE
Inner loop code runs after other outer loop code is iterated

### ISSUE THREAD

**Issue by rudolphh** [lukehaas/RunJS#247]
![bug](https://user-images.githubusercontent.com/949014/116614974-7d6ede00-a8ef-11eb-9d40-5d45d2816967.png)
<img width="519" alt="Screen Shot 2021-04-29 at 1 16 06 PM" src="https://user-images.githubusercontent.com/949014/116614984-82339200-a8ef-11eb-8e32-eadcaa8cd9b6.png">

**Comment by rudolphh** [comment]
Seems that it applies the same logic for code after the inner loop as well.  

So outer loop code before (the inner) runs before, and outer loop code that comes after (the inner) loop runs after. 

<img width="1196" alt="Screen Shot 2021-04-29 at 1 38 42 PM" src="https://user-images.githubusercontent.com/949014/116615921-d68b4180-a8f0-11eb-848e-6a72a32e81cb.png">

**Comment by lukehaas** [comment]
Hi @rudolphh, the reason you're seeing the output ordered in this was is because RunJS is matching the output lines to the originating line in the source code.

You can turn this behaviour off in the preferences:

![Screenshot 2021-04-30 at 09 41 51](https://user-images.githubusercontent.com/741344/116671310-b2833b00-a998-11eb-9db6-583794e3d6a9.png)

**Comment by rudolphh** [comment]
I had a feeling I was missing something. Thank you.

**Comment by lukehaas** [comment]
No worries 😉
