### ISSUE TITLE
Node Version Manager & TS Version Environment's Support

### ISSUE THREAD

**Issue by lordlycastle** [lukehaas/RunJS#280]
Is there currently support for `nvm`? If so how do we set & see which version of `node` and `npm` is it using? How can we change the versions? 

This should be also visible for which version of TypeScript it is using, otherwise you cannot see and might not get why latest features aren't working.

It would be awesome if it also had a 'Console' window which showed exactly the command it runs to run the script and the output; similar to integrated console in IntelliJ/Postman.

When you install packages do you also need to install their own typings package as well`@type/<package name>`?

**Comment by lukehaas** [comment]
RunJS doesn't support nvm because it uses its own internal Node and NPM versions. The version of Node is documented on this readme: https://github.com/lukehaas/RunJS/blob/master/README.md work to improve the documentation is ongoing and I'll aim to also document the NPM and TypeScript versions.

Currently, you do need to also install the typings for the packages you're installing.

**Comment by lordlycastle** [comment]
Thanks for the info. It would be best to support `nvm` as we all work with many versions of node. Same goes for TS version.

Being packaged in app is better when you don't have node installed, but it limits you and you need app updates to update node. I imagine they don't have same release frequency.

**Comment by lukehaas** [comment]
RunJS used to do it like that and rely on the system node and npm but it proved to be very fragile and would break for a variety of reasons. It was also challenging to debug those issues due to having such a dependence on the setup of the user.
It's proved to be a much more robust solution to bundle this internally.

**Comment by lordlycastle** [comment]
I see. Maybe best of both world and allow advanced users to use their own environments? I get this for both JS and TS; and JS is a very beginner friendly language so many are novice with much knowledge of the runtime environment as you don’t need to learn it. 

It obviously can be done as IntelliJ and VSCode support it. 

At the very least, you should allow changing the version by bundling any LTS and Stable versions. The app can download node in application support maybe as required. 

There are many options experienced users would be happy with to be able to change the version of TS and node e.g. env vars. Otherwise this tool is aimed at beginners only ATM.

**Comment by lukehaas** [comment]
I'm not aware of IntelliJ and VSCode supporting NPM package management, are you certain they do this?

One example of an app that does this and relies on the system NPM is an app called Electron Fiddle but they seem to get a lot of support requests from people with NPM errors and people asking them why they don't just bundle NPM. Such as this: https://github.com/electron/fiddle/issues/193

In a scenario where the system Node/NPM is needed to install a package, I'd recommend using the 'Set Working Directiory' option:
![Screenshot 2021-07-22 at 09 55 22](https://user-images.githubusercontent.com/741344/126613788-88ed4b56-8025-43fd-b907-57c469b3a0cd.png)
This will enable you to import packages from a chosen directory.
