### ISSUE TITLE
Spread Operators do not work

### ISSUE THREAD

**Issue by artem-alek** [lukehaas/RunJS#292]
I am not sure what ECMAscript this is using but spread operators do not work. Is there a way to get them to work?

**Comment by jonniedarko** [comment]
I feel this should still work without the console logging

**Comment by jonniedarko** [comment]
@lukehaas sorry for delay responding, but I get this when I try to do the same, I did seem to spot it doesn't error if I add semi-colons but I don't feel I should since js doesn't require it
![Screen Shot 2022-09-29 at 12 21 17 PM](https://user-images.githubusercontent.com/3673943/193085616-c67d01d5-90cb-47be-800b-c492c3f024ff.png)

**Comment by lukehaas** [comment]
thanks, @jonniedarko. I see what the issue is. This is one of the rare edge cases where semi-colons are essential.
You're right, JS doesn't require them but leaving them out does create errors in a small number of cases.
