### ISSUE TITLE
Multiple intermediate variables on root level causes errors

### ISSUE THREAD

**Issue by lordlycastle** [lukehaas/RunJS#370]
I've noticed that the follow is valid code but causes error in RunJS.
```ts
(new Date()).toLocaleString()
(new Date()).toDateString()
// error: TypeError: (intermediate value).toLocaleString(...) is not a function
```
It also happens when you evaluate variables at root level, for example.
```ts
const x = 'hello world';
x.padEnd(9)
(new Date()).toDateString()
// error: TypeError: x.padEnd(...) is not a function
```

Version: 2.1.3

**Comment by lukehaas** [comment]
This is due to a missing semi-colon. If you try this, it works:
```
(new Date()).toLocaleString();
(new Date()).toDateString()
```
This is just one of the scenarios in JS where a semi is essential.

**Comment by lukehaas** [comment]
@lordlycastle I'm closing this now, just wanted to reiterate that this is not a RunJS issue, this is an expected error message due to invalid code. 
The same result can be seen in the Chrome console:

![Screenshot 2021-12-09 at 17 15 06](https://user-images.githubusercontent.com/741344/145855833-7d609f2b-d24b-4ff5-ac24-b5a04f8a8f3f.png)
