### ISSUE TITLE
agressive autocomplete

### ISSUE THREAD

**Issue by craigz** [lukehaas/RunJS#402]
running an activated version 2.3.0 (2.3.0) on an M1 (arm64) MacBook Air running macOS 12.2.1 (21D62).

if i pause for more than 2 or 3 seconds while typing, a line-ending semicolon and carriage return are entered on my behalf. this happens whether or not an autocomplete suggestion is available and was happening in the app's unregistered state as well. 

i've just installed a fresh copy on an intel mac, running a newer (beta) monterey build and observed the same behavior. however, further troubleshooting has isolated the issue.

with `Enable format on run with Prettier` enabled in `Preferences` > `Formatting` and the default formatting rule: 
```prettier
{
"singleQuote":true
}
```
enabled, the described behavior occurs. 

with the formatting option unselected, the expected behavior returns. as in i can pause while typing and the line won't be ended until i enter the return key. 

i've captured a short session showing the behavior, in the recording, i'd only typed the characters shown, while RunJS/Prettier added the `;  \n` to the end of each line. 

**note:** it appears that the loop setting didn't stick, so the animated gif runs once, it seems the best way to view the animated gif to see the behavior is to click on the image which on my browser opens in a new window and runs the animation from the beginning.

![runJS_ghostReturns](https://user-images.githubusercontent.com/1929275/153788641-9c2e7297-1f97-40a7-8e5e-3a0eaac42e50.gif)

<img width="712" alt="runJS_formattingPrefs" src="https://user-images.githubusercontent.com/1929275/153785978-87fc0065-beab-4529-a911-a2194f9403a2.png">

**Comment by lukehaas** [comment]
Thanks @craigz. The behaviour you're seeing is not related to autocomplete, it's Prettier.
As you've rightly spotted this happens when 'Format on run' is enabled (this is off by default) and when you also have 'auto-run' enabled. 
When auto-run is enabled, RunJS executes your code when you stop typing. If you also have format on run enabled then RunJS will execute and also format your code when you stop typing. Both of these behaviours can be disabled in the preferences.
