### ISSUE TITLE
Support Cascadia Code ( Mac )

### ISSUE THREAD

**Issue by pedroslp** [lukehaas/RunJS#404]
Doesn't work well in mac the Cascadia Code font.

<img width="1199" alt="Captura de pantalla 2022-02-18 a las 13 02 08" src="https://user-images.githubusercontent.com/78103538/154679475-8a7b9e90-7efb-47b6-b856-71ebafb815ff.png">

**Comment by lukehaas** [comment]
@pedroslp this is due to a discrepancy between the file name and the font name. The font is "Cascadia Code PL" but the file is "CascadiaCodePL". 
I'll aim to handle this scenario in the next release. 
For now, you could resolve this by updating the font file on your mac to match the font name "Cascadia Code PL"

**Comment by lukehaas** [comment]
This should now be resolved in the latest release - 3.2.1 @pedroslp
