### ISSUE TITLE
Duotone Dark Sky theme no longer available

### ISSUE THREAD

**Issue by adjohnston** [lukehaas/RunJS#473]
This is not a major thing but I noticed after the recent update that Duotone Dark Sky is no longer available as a theme in 2.6.0 (17th August update). It's removal is not mentioned in the change notes. I'm a big fan of this theme (and Duotones in general). Any chance of it making a return?

**Comment by lukehaas** [comment]
Yes, Duotone Dark Sky was removed in the last release. I've been working on improving the selection of themes by adding requested themes. In order to avoid bloat I've also been removing some themes that I considered to be of a lower standard.

I'm fine with reconsidering Duotone if you and possibly others feel strongly about it.

**Comment by adjohnston** [comment]
I'm probably in the minority but custom theming might be nice in a similar manner to how iTerm2 handles it. Anyways. Thanks for the good work with this project. I find it very valuable.

**Comment by lukehaas** [comment]
After giving Duotone another look, I've reinstated Duotone Dark in the latest release.
