### ISSUE TITLE
it's simple loop, but it can't 

### ISSUE THREAD

**Issue by dembee111** [lukehaas/RunJS#477]
let isArr = [1,2,3,5,4,6,7,8]

isArr.forEach((arr, index) => {
  if(arr === index + 1){
    console.log('true', arr, index + 1)
  }else{
    console.log('false')
  }
})

**Comment by btecu** [comment]
What is the issue?
<img width="629" alt="image" src="https://user-images.githubusercontent.com/7517745/190645561-71b62888-be29-4b9b-962c-ffece4545211.png">

**Comment by lukehaas** [comment]
@dembee111 without any detail I can't be sure what the issue is here, but my guess would be it relates to the order of the output.

If you want to display the output in its natural order of execution, disable the match lines option.
![Screenshot 2022-09-17 at 13 13 21](https://user-images.githubusercontent.com/741344/190856263-d138be65-8d30-4e9e-b390-e6620a072c35.png)


![Screenshot 2022-09-17 at 13 13 46](https://user-images.githubusercontent.com/741344/190856265-34f0f9db-d091-4ea1-9b52-2af37cce1ee3.png)

**Comment by dembee111** [comment]
thank you
