### ISSUE TITLE
Intl.DateTimeFormat does not return correct time

### ISSUE THREAD

**Issue by Ravetracer** [lukehaas/RunJS#491]
Hi,
I wanted to try out some date/time related stuff before implementing it in my project and stumbled over some strange behaviour in RunJS.

The result of my code (screenshot attached) should show 15:40:30 and not 14:40:30. There's one hour difference between UTC and the real German time zone here. I also tested it in jsFiddle and codepen where the result was correct.

![intl_datetimeformat](https://user-images.githubusercontent.com/2032218/195856932-a194c4e4-c9c0-4e25-b16a-37ca43627093.png)

**Comment by lukehaas** [comment]
Thanks, @Ravetracer. Just so I can get a clear idea of the issue here:
The UTC time you're setting is 13:40:30.
GMT is the same as UTC so the time in London is the same, 13:40. 
Berlin is an hour ahead of London, so the 13:40:30 UTC time should be 14:40:30 in Berlin.
What am I missing here?

![Screenshot 2022-10-14 at 14 35 28](https://user-images.githubusercontent.com/741344/195861267-ad143443-769b-49be-b5b8-8e5f84ae9c1d.png)

**Comment by Ravetracer** [comment]
Oh dear, I made a mistake. Currently it's "summer time" in Germany so it's UTC+2 but from Oct. 30th it's UTC+1 again. 
I hate this summer/winter time switch. It's useless. 
But still thank you for your time and investigation!
