### ISSUE TITLE
for loop print twice, instead of once

### ISSUE THREAD

**Issue by mandaputtra** [lukehaas/RunJS#76]
I actually don't know how to call this issue.  But here is the images, in this snippet `console.log()` should fire up once right?

![onlyprintone](https://user-images.githubusercontent.com/23342943/58497959-9d4f7180-81af-11e9-836b-98b80c5c9516.PNG)

**Comment by lukehaas** [comment]
This isn't a duplicate console.log output, RunJS is outputting the result of the line `result += parseInt(strNumber.charAt(i))` and also the output of `console.log(result)`.
So there isn't really any need to have the `console.log(result)`

**Comment by mandaputtra** [comment]
Oh I okay then thanks for the explanation 😃

**Comment by lukehaas** [comment]
👍 @mandaputtra if you would prefer RunJS to just show the output of your whole source instead of each line, then there is an option in the advanced preferences called 'Holistic Evaluation' that will do this.

![Screenshot 2019-05-29 at 14 54 44](https://user-images.githubusercontent.com/741344/58562734-bc86e700-8221-11e9-891e-c1d8ee6347e8.png)
